# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base box - Ubuntu 24.04 LTS
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "~> 20241002.0.0"

  # NAS Server Simulation - Single powerful VM
  config.vm.define "nas-server" do |nas|
    nas.vm.hostname = "nas-server"
    nas.vm.network "private_network", ip: "192.168.56.100"
    
    # Port forwarding for web services
    nas.vm.network "forwarded_port", guest: 80, host: 8080      # ZimaOS Web UI
    nas.vm.network "forwarded_port", guest: 9000, host: 9000    # Portainer
    nas.vm.network "forwarded_port", guest: 445, host: 445      # Samba (if enabled)
    
    # Resource allocation to simulate GMKTec NucBox G9
    nas.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"  # 4GB RAM
      vb.cpus = 4         # Quad core
      vb.name = "ragna-nas-server"
      
      # Create 3 additional disks for ZFS testing and storage
      (1..3).each do |i|
        disk_file = "./zfs-disk-#{i}.vdi"
        unless File.exist?(disk_file)
          vb.customize ["createhd", "--filename", disk_file, "--size", 10240] # 10GB each
        end
        vb.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", i + 1, "--device", 0, "--type", "hdd", "--medium", disk_file]
      end
    end
    
    # Provision with Ansible
    nas.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../ragna-nas/zimaos-nas/playbooks/site.yml"
      ansible.inventory_path = "inventory.ini"
      ansible.verbose = "v"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end

  # Initial provisioning for all nodes
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip curl wget
    # Install Docker prerequisites
    apt-get install -y apt-transport-https ca-certificates gnupg lsb-release
    echo "ragna-nas test environment" > /etc/motd
  SHELL
end