---
- name: Install Portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    ports:
      - "{{ portainer_port }}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart_policy: unless-stopped