---
- name: Full ZimaOS Site Configuration
  hosts: all
  become: true

  roles:
    - { role: docker, tags: [docker] }
    - { role: zimaos, tags: [zimaos] }
    - { role: portainer, tags: [portainer] }
    - { role: netplan, tags: [netplan] }
    - { role: firewall, tags: [firewall] }
    - { role: lubuntu, tags: [lubuntu, desktop] }